import openai
import requests

invoice_description = "YOGURT,PLN BLNDED LOW FAT"

keywords = [
    "Alcohol beverages",
    "Beverage services",
    "sea Food suppliers",
    "Internet services",
    "wireless equipment",
    "Wireless services",
    "Lodging Franchisor and Hospitality",
    "IT services",
    "signage",
    "social Media",
    "social Media Management",
    "Contract labor",
    "Paving Contractors",
    "Payment source services",
    "staffing & recruitment services",
    "Access controls",
    "Accounting services",
    "Accounting software for businesses",
    "administers motor vehicle registration and driver licensing",
    "Administration services",
    "Association - Membership fee",
    "Billing services",
    "business licensing",
    "Business services",
    "CCTV - Access controls",
    "Document Destruction services",
    "Dues & subscriptions",
    "Human resources",
    "Inspection and Certification",
    "Inspection and safety",
    "Labour law compliance regulation services",
    "Legal services",
    "Licensing",
    "locksmith and security installation and services",
    "manpower",
    "monitoring services",
    "Penalities",
    "Production and Distribution services",
    "Professional HandyMan services",
    "Professional services",
    "Professional Training and Coaching",
    "security services",
    "security systems",
    "special event permitting",
    "sports venues",
    "Uniforms and Apparel",
    "vacation rentals",
    "Automobile leasing and renting solutions",
    "Automobile leasing and Repair services",
    "computer and networking equipment",
    "Computer repair services",
    "Computer security services",
    "Cyber security",
    "fully-services hardware store",
    "Hospitality Communication solutions",
    "Hospitality software",
    "Hospitality software solutions",
    "networking equipment",
    "networking services",
    "Software services",
    "Technical support services",
    "Technology services",
    "Telecommunication services",
    "alarm systems",
    "Architectural millwork",
    "Automatic Manual and sectional doors",
    "Backflow Testing & Repair services",
    "Battery and portable power solutions",
    "Building & Life safety",
    "Building supplies",
    "Cable TV services",
    "carpentry services",
    "carpet",
    "Ceiling services",
    "ceramic and porcelain tiles",
    "Chemicals",
    "Coating solutions",
    "commercial food services Equipment",
    "Commercial Refrigeration & Appliance",
    "concrete services",
    "Construction services",
    "consumer appliances",
    "Cooking Equipment services",
    "Corporate housing properties",
    "Custom Window Treatments & services",
    "Cutting Edge sharpening services",
    "Dock Equipment",
    "Dry wall services",
    "electical services",
    "Electric vehicle charging stations",
    "Electric vehicles",
    "Electrical equipment",
    "Electrical security services",
    "electrical services",
    "electrical supplies",
    "Electronic supplies",
    "Elevator services",
    "Emergency services",
    "engineering services",
    "Environmental services",
    "equipment supplies",
    "Excavating services",
    "exterior and interior building products",
    "Fabricator of exceptional cabinetry and millwork",
    "fire alarm security sprinkler services",
    "Fire alarm systems",
    "Fire ext. maintenance",
    "fire protection and life safety",
    "Fitness Equipment repairs",
    "Fitness services",
    "furniture and fixtures",
    "Garden services",
    "Generator - sale and installation",
    "Generator Repairs",
    "grease",
    "hardscaping",
    "health care",
    "home appliances",
    "Horticulture",
    "Hotel Key Cards",
    "HVAC services",
    "Ice Machine repair services",
    "industrial equipment supplies",
    "infrastructure solutions",
    "Installation and Repair services",
    "Insulation",
    "Interior Design services",
    "irrigation",
    "Kitchen services",
    "Landscaping",
    "Lightining Equipment",
    "logistics services",
    "Maintenance of commercial food Equipment services",
    "mechanical process equipment",
    "Medical equipment services",
    "medical journal",
    "Medical services",
    "metals fabrication and erection",
    "natural stone fabrication services",
    "outdoor power equipments sales and services",
    "Painting services",
    "Paper shredding",
    "Pest Control",
    "plumbing services",
    "Plumbing supplies",
    "Pond contractor",
    "Pool Equipment",
    "Pool services",
    "portable power solutions",
    "Refrigeration services",
    "Renovations",
    "Rental services",
    "repair and operations services",
    "Repair services",
    "Repairs - Landscaping",
    "Restoration services",
    "Roofing services",
    "safety equipment supplier services",
    "safety services",
    "security and life safety systems",
    "services for restoration",
    "sharpening services",
    "sports Equipment",
    "sprinkler systems",
    "storage services",
    "Television",
    "Towing services",
    "tree removal",
    "Turf equipment",
    "Vehicle repairs",
    "Vehicle spare parts",
    "warehouse management",
    "welding services",
    "Wellness and Fitness services",
    "wildlife control services",
    "wood Cleaning services",
    "Advertising",
    "campaigns",
    "charity",
    "counseling services",
    "digital marketing services",
    "Digital printing services",
    "Flags",
    "Graphic Design services",
    "Marketing services",
    "Photography",
    "Public Relations",
    "Web Design services",
    "Catering services",
    "Glass services",
    "trophys",
    "magazine",
    "Restaurants supplies",
    "Business supplies & Equipment",
    "courier services",
    "Delivery services",
    "Dish washing",
    "Educational Institution",
    "Floor Care",
    "housekeeping",
    "Media services",
    "Music and Entertainment",
    "Newspaper",
    "Office supplies",
    "Plastic products",
    "storm Raincover",
    "supplier of paper",
    "Toys",
    "Accommodiation services",
    "cleaning equipment",
    "cleaning machines",
    "Cleaning services",
    "Cleaning supplies",
    "Clothing",
    "Consumer Goods",
    "Craft store",
    "Disinfecting",
    "Entertainment services",
    "Event services",
    "Facilities services",
    "Flower services",
    "grocery delivery services",
    "guest supplies",
    "hospitality and manpower services",
    "Hospitality procurement services",
    "hospitality products",
    "Hot Tub Water Delivery",
    "Hotel amenities",
    "Laundry",
    "Linen",
    "packaging services",
    "printing services",
    "Reliable maintenance",
    "Textile services",
    "The Home Depot",
    "Travel services",
    "Wallpaper stores",
    "Architecture",
    "Consulting services",
    "Design services",
    "pre-development consultation assistance",
    "Tax consulting services",
    "Taxes",
    "meeting facilities",
    "Food and Beverage services",
    "fruits & vegetables",
    "Hospitality",
    "acquiring profitable waste",
    "Biohazard Cleaning & Remediation services",
    "Electricity",
    "Gas",
    "gas station",
    "Oil",
    "petrol and gas station",
    "remediation services",
    "renewable energy",
    "Sanitation services",
    "Utilities",
    "Waste management services",
    "Water services",
    "Water treatment - softner",
    "Carts",
    "Containers recycling services",
    "Convenience store",
    "Financial services",
    "Gift shop",
    "Insurance services",
    "leasing services",
    "parking management services",
    "Payroll services",
    "real estate services",
    "Road services",
    "speed monitoring services",
    "Tourism services",
    "VIideo monitoring services",
    "waste water services",
]

quoted_keywords = ['"{}"'.format(keyword) for keyword in keywords]

prompt = f"Classify the following invoice line item description:\n\n\"{invoice_description}\"\n\nKeywords: {', '.join(quoted_keywords)}"

key = "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"

response = requests.post(url='https://api.openai.com/v1/chat/completions',
                        headers={'Content-Type': 'application/json', 'Authorization': f'Bearer {key}'},
                        json={
                            "model": "gpt-4",
                            "messages": [
                                {"role": "system", "content": "You are a helpful assistant."},
                                {"role": "user", "content": prompt}
                            ]
                        }
                        )

classification = response.json()['choices'][0]['message']['content'].strip()

print(f"Classification: {classification}")


